version: "3.7"
services:
  web:
    image: go-clean-arch
    container_name: sticker_api
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config.json:/stickerapi/config.json


  mysql:
    image: mysql:5.7
    container_name: sticker_mysql
    command: mysqld --user=root
    volumes:
      - ./sticker.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE='dummy'
      - MYSQL_USER=user
      - MYSQL_PASSWORD='123456'
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "ping", "-h", "localhost:9090"]
      timeout: 5s
      retries: 10






